spring.application.name = shady
google.api.key = AIzaSyDrZQrmP3IAmb2hUnHqOBmp1ErkpLhS_ms
google.routes.base-url = https://routes.googleapis.com
osm.overpass.base-url = https://overpass-api.de/api
spring.datasource.url = jdbc:postgresql://localhost:5432/shady_db
spring.datasource.username = postgres
spring.datasource.password = newpassword